spring:
  application:
    name: redisjtv-server
  security:
    user:
      name: root
      password: root

server:
  port: 8084
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#            defaultZone: http://localhost:8761/eureka/
            defaultZone: http://root:root@localhost:8761/eureka
#             defaultZone: http://user:password@localhost:8761/eureka
  instance:
    hostname: localhost     
    


